[package]
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
name = "PaRTyS"
version = "0.1.0"

[dependencies]
cgmath = "0.12.0"
num-traits = "0.1.36"
piston2d-opengl_graphics = "0.36.2"
piston_window = "0.60.0"
time = "0.1"
